#!/usr/bin/expect --
#
if { [llength $argv] != 2 } {
   puts "usage: $argv0 remote_file local_file"
   exit 1
}

set remote_file [lindex $argv 0]
set local_file [lindex $argv 1]

set timeout -1
spawn scp $env(SCP_USERNAME)@$env(SCP_REMOTE_HOST):$remote_file $local_file 
expect "Password:"
send "$env(SCP_PASSWORD)\r"
expect "100%"
interact
